* My Emacs config

This is a simple Emacs config. It starts up quickly and works well in
gui and terminal.

It is tested on:

- GNU/Linux, both gui and terminal.
- emacs-nox on Windows Subsystem for Linux.

** Installation

You can use this config by cloning the repo to your home
directory(please back up your own config first). Required packages
will be installed automatically if you have internet access.

if emacs reports some packages are not found, please start emacs by

#+BEGIN_SRC shell
emacs -Q
#+END_SRC

and run =M-x package-refresh-contents=.

Note, emacs 26 is required.


** Theme

The color theme used in this config is [[https://github.com/abo-abo/eclipse-theme][abo-abo/eclipse-theme]], which is
light background and works quite well both on gui and terminal.  The
color theme falls back to dark background with a nice look up in
emacs-nox(since there is bug displaying emacs on WSL, I use
[[https://github.com/goreliu/wsl-terminal][goreliu/wsl-terminal]] instead of the default terminal).

The config also provides two functions to automatically choose Chinese
font size to match the English font size:
=set-twice-en-width-han-font-size= and
=set-same-en-height-han-font-size=, which are quite useful for aligning
contents in org-mode tables.


** Completion

=ivy=, =counsel= and =swiper= are used for interactively command
selection and searching.

=company= and =lsp-mode= are used for code highlight, navigation and
completion.

=yasnippet= provides a code template system.

** Project management

The config uses these packages for project management:

- =magit=, a =git= interface for emacs for version control.
- =projectile=, a project interaction library.
- =treemacs=, a tree-like file and project explorer.

** Org mode

Config refile targets, capture templates and html export settings for org mode. 
Integrate Chinese lunar holidays with org agenda using =cal-china-x= package.


** Finally...

Have fun!
