#+TITLE: My Emacs config

This is a simple Emacs config. It starts up quickly and works well in
gui and terminal.

It is tested on:

- GNU/Linux, both in gui and terminal.
- emacs-nox on Windows Subsystem for Linux.
- Emacs-mac on Mac OS X

Emacs 26+ is required for thread support.

* Installation

You can use this config by cloning the repo to your home
directory(please back up your own config first). Required packages
will be installed automatically if you have internet access.

if Emacs complains some packages are not found, please run
 =M-x package-refresh-contents= and restart.

* Keybindings and Package management

I use Emacs default keybindings. =evil= is also fantastic, but I'm not
an expert of vim...

To avoid "Emacs pinky", I switch right ALT with right CTRL(I don't use
it anyway), so I can use right thumb to press CTRL.

Packages are managed by =use-package=.

* Theme

The color theme used in this config is [[https://github.com/abo-abo/eclipse-theme][abo-abo/eclipse-theme]], which is
light background and works quite well both in gui and terminal. The
color theme falls back to default dark background with a nice look in
emacs-nox(since there is bug displaying emacs on WSL, I use
[[https://github.com/goreliu/wsl-terminal][goreliu/wsl-terminal]] instead of the default terminal).

The config uses =emacs-zh-align= to config =han, kana, cjk-mis= and
other similar scripts and other charsets' font size to make them be
compatible with English font size in tabular like environment, see
[[https://github.com/chen-chao/emacs-zh-align][emacs-zh-align]] for detail.


* Completion

I use =ivy= as the completion frontend, which is simple and very powerful.
=counsel= and =swiper comes along as interactively command
selection and searching tools. A few tips:

- =M-n= and =M-j= in =swiper= could select and expand text under cursor.
- =M-q= could replace the matching candidates.

=company= are used as the completion backend.

=yasnippet= provides a code template system.

* Major modes

=lsp-mode= are used for code highlight, navigation and completion for:

- golang(gopls)
- python(pyls)
- c/c++/object-c via =ccls=
- java via =lsp-java=

Other support languages or major modes:

- protobuf
- markdown
- yaml
- octave
- asymptote

* Project management

The config uses these packages for project management:

- =magit=, a =git= interface for emacs for version control.
- =projectile=, a project interaction library.
- =treemacs=, a tree-like file and project explorer.

* Org mode

Config refile targets, capture templates and html export settings for org mode. 
Integrate Chinese lunar holidays with org agenda using =cal-china-x= package.


* Finally...

Have fun!
